import type { HistoryEntry } from "./history-entry";
export const historyFixtures = [
  {
    key: "s1",
    at: 1791297360000,
    code: "K7QX2MPA",
    level: "ふつう",
    players: 4,
    rank: 1,
    total: 128.4,
    sim: 91.2,
    speed: 16,
    bonus: 9,
    gens: 3,
    art: "pink.twin.blue.sailor.smile.sky",
    cats: {
      char: 94.1,
      tag: 88.6,
      content: 90.3,
      pose: 89.8,
    },
    ranking: [
      {
        name: "ねこぜ",
        isMe: true,
        rank: 1,
        total: 128.4,
        art: "pink.twin.blue.sailor.smile.sky",
      },
      {
        name: "ぴよ丸",
        isMe: false,
        rank: 2,
        total: 101.7,
        art: "pink.bob.blue.sailor.smile.sky",
      },
      {
        name: "ぴくせる侍",
        isMe: false,
        rank: 3,
        total: 90.6,
        art: "blonde.twin.red.hoodie.wink.white",
      },
      {
        name: "プロンプト職人",
        isMe: false,
        rank: null,
        total: null,
        art: null,
      },
    ],
    prompt: "",
  },
  {
    key: "s2",
    at: 1791280080000,
    code: "K7QX2MPA",
    level: "ふつう",
    players: 4,
    rank: 3,
    total: 88,
    sim: 70.4,
    speed: 11,
    bonus: 6,
    gens: 4,
    art: "blonde.long.red.hoodie.wink.white",
    cats: {
      char: 66.2,
      tag: 74.9,
      content: 71.8,
      pose: 68,
    },
    ranking: [
      {
        name: "ぴよ丸",
        isMe: false,
        rank: 1,
        total: 112.3,
        art: "pink.twin.blue.sailor.calm.sky",
      },
      {
        name: "プロンプト職人",
        isMe: false,
        rank: 2,
        total: 95.1,
        art: "pink.bob.green.sailor.smile.white",
      },
      {
        name: "ねこぜ",
        isMe: true,
        rank: 3,
        total: 88,
        art: "blonde.long.red.hoodie.wink.white",
      },
      {
        name: "ぴくせる侍",
        isMe: false,
        rank: 4,
        total: 61.2,
        art: "black.bob.green.dress.calm.room",
      },
    ],
    prompt: "",
  },
  {
    key: "s3",
    at: 1791202320000,
    code: "3TA9AXBK",
    level: "かんたん",
    players: 2,
    rank: 1,
    total: 112.6,
    sim: 86.1,
    speed: 14,
    bonus: 12,
    gens: 2,
    art: "pink.bob.blue.sailor.smile.white",
    cats: {
      char: 89,
      tag: 83.4,
      content: 87.2,
      pose: 84.9,
    },
    ranking: [
      {
        name: "ねこぜ",
        isMe: true,
        rank: 1,
        total: 112.6,
        art: "pink.bob.blue.sailor.smile.white",
      },
      {
        name: "ぴよ丸",
        isMe: false,
        rank: 2,
        total: 97.5,
        art: "pink.twin.red.sailor.smile.white",
      },
    ],
    prompt: "",
  },
  {
    key: "s4",
    at: 1791046800000,
    code: "R8VA8J4G",
    level: "むずかしい",
    players: 3,
    rank: 2,
    total: 79.3,
    sim: 64.8,
    speed: 8,
    bonus: 6,
    gens: 4,
    art: "silver.long.green.dress.calm.room",
    cats: {
      char: 58.3,
      tag: 70.2,
      content: 66.1,
      pose: 63.9,
    },
    ranking: [
      {
        name: "ぴくせる侍",
        isMe: false,
        rank: 1,
        total: 84,
        art: "blonde.long.blue.dress.smile.room",
      },
      {
        name: "ねこぜ",
        isMe: true,
        rank: 2,
        total: 79.3,
        art: "silver.long.green.dress.calm.room",
      },
      {
        name: "ぴよ丸",
        isMe: false,
        rank: 3,
        total: 70.8,
        art: "blue.twin.green.hoodie.wink.room",
      },
    ],
    prompt: "",
  },
  {
    key: "s5",
    at: 1790787600000,
    code: "C4TEJMM5",
    level: "かんたん",
    players: 2,
    rank: null,
    total: null,
    sim: null,
    speed: null,
    bonus: null,
    gens: 5,
    art: null,
    cats: null,
    ranking: [
      {
        name: "ぴよ丸",
        isMe: false,
        rank: 1,
        total: 93.4,
        art: "pink.twin.blue.hoodie.smile.white",
      },
      {
        name: "ねこぜ",
        isMe: true,
        rank: null,
        total: null,
        art: null,
      },
    ],
    prompt: "",
  },
] satisfies HistoryEntry[];
