import { defineRecipe } from "@pandacss/dev";
import { textFocus } from "./control";
export const link = defineRecipe({
  className: "link",
  base: {
    textStyle: "body.md",
    color: "action.link.fg",
    textDecorationLine: "underline",
    textUnderlineOffset: "0.2em",
    borderRadius: "0",
    _hover: { textDecorationThickness: "2px" },
    _focusVisible: textFocus,
  },
  variants: {
    appearance: {
      back: {
        display: "inline-flex",
        alignItems: "center",
        gap: "3",
        color: "fg.default",
        textStyle: "label.supporting",
        textDecorationLine: "none",
        _hover: { color: "accent.primary" },
      },
      text: {},
      inverse: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "3",
        padding: "0.5rem 0.95rem",
        borderRadius: "full",
        background: "bg.inverse",
        color: "fg.inverse",
        textStyle: "label.supporting",
        textDecorationLine: "none",
        minHeight: "control.0",
      },
      subtle: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "3",
        minHeight: "control.0",
        minWidth: "control.0",
        paddingInline: "5",
        background: "bg.subtle",
        color: "fg.default",
        borderRadius: "full",
        textStyle: "label.supporting",
        textDecorationLine: "none",
        _navigationCompact: {
          paddingInline: "0",
          minHeight: "control.0",
          minWidth: "control.0",
          position: "relative",
          isolation: "isolate",
          background: "transparent",
          "&::before": {
            content: '""',
            position: "absolute",
            inset: "2px",
            borderRadius: "full",
            background: "bg.subtle",
            zIndex: -1,
          },
        },
      },
      scroll: {
        display: "grid",
        justifyItems: "center",
        gap: "3",
        minWidth: "control.0",
        textStyle: "eyebrow",
        color: "fg.muted",
        textDecorationLine: "none",
        animation: "scrollHintEnter 400ms ease-out 600ms both",
        _motionReduce: { animation: "none" },
        "&::after": {
          content: '""',
          width: "2px",
          height: "2.5rem",
          background:
            "linear-gradient(token(colors.accent.primary) 50%, token(colors.border.default) 50%) 0 0 / 100% 200%",
          animation: "scrollHint 1600ms ease-in-out infinite",
          _motionReduce: { animation: "none" },
        },
      },
      quiet: {
        color: "fg.muted",
        textStyle: "body.sm",
        textDecorationLine: "underline",
      },
      navigation: {
        display: "inline-flex",
        alignItems: "center",
        gap: "3",
        minHeight: "control.0",
        minWidth: "control.0",
        justifyContent: "center",
        color: "fg.default",
        textStyle: "label.supporting",
        textDecorationLine: "none",
        position: "relative",
        fontSize: "0.95rem",
        letterSpacing: "0.04em",
        transition: "color 300ms ease",
        _hover: { color: "accent.primary" },
        _motionReduce: { transition: "none" },
        "&[aria-current]:not([aria-current=false])::after": {
          content: '""',
          position: "absolute",
          insetInline: "0",
          bottom: "0",
          height: "3px",
          borderRadius: "full",
          background: "accent.primary",
        },
      },
    },
  },
  defaultVariants: { appearance: "text" },
});
