import { defineRecipe } from "@pandacss/dev";

export const text = defineRecipe({
  className: "text",
  base: { margin: "0" },
  variants: {
    wrap: { normal: {}, balance: { textWrap: "balance", wordBreak: "auto-phrase" } },
    align: {
      start: { textAlign: "start" },
      center: { textAlign: "center" },
      end: { textAlign: "end" },
    },
    tone: {
      highlight: { color: "accent.highlight" },
      default: { color: "fg.default" },
      muted: { color: "fg.muted" },
      inverse: { color: "fg.inverse" },
      success: { color: "status.success.fg" },
      danger: { color: "status.danger.fg" },
      accent: { color: "accent.primary" },
      primary: { color: "action.link.fg" },
      secondary: { color: "fg.accent.secondary" },
      "accent-secondary": { color: "accent.secondary" },
      subtle: { color: "fg.subtle" },
      supporting: { color: "fg.supporting" },
    },
    variant: {
      "label.name": { textStyle: "label.name" },
      "numeric.inline": { textStyle: "numeric.inline" },
      "numeric.remainder": { textStyle: "numeric.remainder" },
      "numeric.score": { textStyle: "numeric.score" },
      "display.announcement": { textStyle: "display.announcement" },
      "display.signal": { textStyle: "display.signal" },
      "display.feedback": { textStyle: "display.feedback" },
      "label.announcement": { textStyle: "label.announcement" },
      "label.artwork": { textStyle: "label.artwork" },
      "label.overline": { textStyle: "label.overline" },
      "label.caption": { textStyle: "label.caption" },
      "numeric.hero": { textStyle: "numeric.hero" },
      inherit: {
        fontFamily: "inherit",
        fontSize: "inherit",
        fontStyle: "inherit",
        lineHeight: "inherit",
        letterSpacing: "inherit",
        fontVariantNumeric: "inherit",
      },
      "body.detail": { textStyle: "body.detail" },
      "body.lead": { textStyle: "body.lead" },
      "body.md": { textStyle: "body.md" },
      "body.sm": { textStyle: "body.sm" },
      "body.prose": { textStyle: "body.prose" },
      label: { textStyle: "label" },
      caption: { textStyle: "caption" },
      "code.compact": { textStyle: "code.compact" },
      code: { textStyle: "code" },
      numeric: { textStyle: "numeric" },
      eyebrow: { textStyle: "eyebrow" },
      "eyebrow.strong": { textStyle: "eyebrow.strong" },
      "label.display": { textStyle: "label.display" },
      "numeric.counter": { textStyle: "numeric.counter" },
      "numeric.display": { textStyle: "numeric.display" },
      "numeric.ordinal": { textStyle: "numeric.ordinal" },
      "numeric.fraction": { textStyle: "numeric.fraction" },
      "numeric.rank": { textStyle: "numeric.rank" },
      "numeric.supporting": { textStyle: "numeric.supporting" },
      "label.fluid": { textStyle: "label.fluid" },
      "label.supporting": { textStyle: "label.supporting" },
    },
    emphasis: {
      "accent-shadow": {
        textShadow:
          "0.06em 0.06em 0 token(colors.accent.primary), 0.12em 0.12em 0 rgb(0 0 0 / 0.25)",
      },
      strong: { fontWeight: "bold" },
      highlight: { fontWeight: "bold", layerStyle: "text.highlight" },
      offset: { textShadow: "text.offset" },
      outline: {
        WebkitTextFillColor: "transparent",
        WebkitTextStroke: "1px currentColor",
        "@media (forced-colors: active)": {
          WebkitTextFillColor: "currentColor",
          WebkitTextStroke: "0",
        },
      },
    },
  },
});
