import base from "@pandacss/preset-base";
// 利用先ごとの成立条件。同じ値でも他のComponentへ自動適用しない。
const twoColumnsMin = "30em";
const wideLayoutMin = "54em";
// アートワークの配置を切り替える条件。Visualの検査もこの一覧を参照する。
export const artworkConditions = {
  artworkNarrow: "@media (max-width: 900px)",
  artworkMedium: "@media (max-width: 1100px)",
  artworkVertical: "@media (orientation: portrait)",
  artworkCompact: "@media (max-width: 560px)",
  artworkPortrait: "@media (min-width: 561px) and (max-width: 1100px) and (orientation: portrait)",
};
export const conditions = {
  segmentedControlCompact: "@media (max-width: 35em)",
  segmentedControlWide: "@media (width > 35em)",
  segmentedControlInline: "@container animic-segmented-control (min-width: 22em)",
  buttonCompact: "@media (max-width: 35em)",
  progressListCompact: "@media (max-width: 35em)",
  footerCompact: "@media (max-width: 35em)",
  footerShort: "@media (min-width: 901px) and (max-height: 800px)",
  collectionCompact: "@media (max-width: 53.75em), (max-aspect-ratio: 1/1)",
  dialogExpandedCompact: "@media (max-width: 53.75em), (max-aspect-ratio: 1/1)",
  avatarGroupNarrow: "@media (max-width: 35em)",
  composerCompact: "@media (max-width: 35em)",
  readoutCompact: "@media (max-width: 35em)",
  readoutNarrow: "@media (max-width: 53.75em)",
  avatarGroupCompact: "@container animic-avatar-group (max-width: 24em)",
  thumbnailCompact: "@media (max-width: 75em)",
  thumbnailLabelCompact: "@media (max-width: 35em)",
  mediaCompact: "@media (max-width: 35em)",
  recordCompact: "@media (max-width: 35em)",
  statGroupNarrow: "@media (max-width: 53.75em)",
  statGroupCompact: "@media (max-width: 35em)",
  podiumCompact: "@media (max-width: 35em)",
  comparisonStageCompact: "@container animic-comparison-stage (max-width: 53.75em)",
  noticeCompact: "@container animic-notice (max-width: 35em)",
  workspaceDocked: "@media (max-width: 35em) and (height > 40em)",
  workspaceFlow: "@media (width > 35em), (height <= 40em)",
  workspaceCompact: "@container animic-workspace (max-width: 53.75em)",
  workspaceNarrow: "@container animic-workspace (max-width: 35em)",
  workspaceVertical: "@container animic-workspace (width < 40em)",
  workspaceTall: "@media (height > 40em)",
  workspaceShort: "@media (max-height: 40em)",
  workspaceLandscape: "@media (min-width: 40em) and (max-height: 40em)",
  workspaceHorizontal: "@container animic-workspace (min-width: 40em)",
  comparisonWide: "@media (min-width: 75em)",
  comparisonNarrow: "@media (max-width: 53.75em)",
  comparisonCompact: "@media (max-width: 35em)",
  tokenInputCompact: "@media (max-width: 51.25em)",
  articleCompact: "@media (max-width: 35em)",
  documentCompact: "@media (max-width: 35em)",
  appFrameCompact: "@media (max-width: 35em)",
  // 本文72remと、その左右にロゴ・外側余白を置く9remずつが収まる幅。
  appFrameBrandBeside: "@media (min-width: 90em)",
  actionBarDocked: "@media (max-width: 51.25em)",
  actionBarCompact: "@media (max-width: 35em)",
  tileCollectionCompact: "@media (max-width: 35em)",
  codeDisplayCompact: "@media (max-width: 35em)",
  splitBalancedColumns: "@container animic-split (min-width: 52em)",
  mediaObjectActionsWide: "@container animic-media-object (min-width: 30em)",
  splitBalanced: "@container animic-split (min-width: 49.25em)",
  focusLayoutCompact: "@media (max-width: 35em)",
  layoutHeaderCompact: "@media (max-width: 35em)",
  ...base.conditions,
  focusVisible:
    "&:is(:focus-visible, [data-focus-visible]):not(:where([data-animic-input=pointer] *))",
  focusWithinVisible: "&:has(input:focus-visible):not(:where([data-animic-input=pointer] *))",
  ...artworkConditions,
  invalid: "&:is([aria-invalid=true], [data-invalid])",
  gridTwo: `@container animic-grid (min-width: ${twoColumnsMin})`,
  gridFull: `@container animic-grid (min-width: ${wideLayoutMin})`,
  splitEqual: `@container animic-split (min-width: ${twoColumnsMin})`,
  splitMedia: "@container animic-split (min-width: 32em)",
  splitIllustrated: "@media (min-width: 901px)",
  numericCompact: "@media (max-width: 900px)",
  splitIntrinsic: "@container animic-split (width > 49.5em)",
  splitShort: "@media (min-width: 901px) and (max-height: 800px)",
  imagePairCompact: "@media (max-width: 35em)",
  surfaceNarrow: "@media (max-width: 35em)",
  surfaceExpanded: "@media (width > 35em)",
  sectionDense: "@media (min-width: 561px) and (max-width: 900px)",
  sectionShort: "@media (min-width: 901px) and (max-height: 800px)",
  splitAsymmetric: `@container animic-split (min-width: ${wideLayoutMin})`,
  dialogCentered: `@container animic-dialog (min-width: ${twoColumnsMin})`,
  dialogCompactCentered: "@container animic-dialog (min-width: 35.001em)",
  imagePairWide: `@container animic-image-pair (min-width: ${twoColumnsMin})`,
  sectionNavigationCompact: "@media (max-width: 900px)",
  clusterCompact: "@media (max-width: 35em)",
  sectionPortrait: "@media (min-width: 561px) and (max-width: 1100px) and (orientation: portrait)",
  stackCompact: "@media (max-width: 900px)",
  actionPortrait: "@media (min-width: 561px) and (max-width: 1100px) and (orientation: portrait)",
  mediaObjectInline: "@container animic-media-object (min-width: 22em)",
  surfaceCompact: "@media (max-width: 900px)",
  carouselWide: "@media (min-width: 901px)",
  carouselNarrow: "@media (max-width: 560px)",
  carouselCompact: "@media (max-width: 900px)",
  sectionWide: "@media (min-width: 901px)",
  sectionCompact: "@media (max-width: 35em)",
  headingCompact: "@media (max-width: 35em)",
  headingPortrait: "@media (min-width: 561px) and (max-width: 1100px) and (orientation: portrait)",
  navigationDense: "@media (min-width: 561px) and (max-width: 900px)",
  navigationWide: "@media (min-width: 901px)",
  navigationConstrained: "@media (min-width: 901px) and (max-width: 1200px)",
  navigationCompact: "@media (max-width: 35em)",
  actionNarrow: "@media (max-width: 400px)",
  actionCompact: "@media (max-width: 35em)",
  layerStack: "@media (max-width: 560px), (max-width: 1100px) and (orientation: portrait)",
  layerPortrait: "@media (min-width: 561px) and (max-width: 1100px) and (orientation: portrait)",
};
