import { defineSlotRecipe } from "@pandacss/dev";
import { focus } from "../control";
export const article = defineSlotRecipe({
  className: "article",
  slots: [
    "root",
    "header",
    "title",
    "section",
    "heading",
    "paragraph",
    "list",
    "table",
    "tableLabel",
    "tableValue",
    "toc",
    "summary",
    "tocList",
    "tocLink",
    "footer",
  ],
  base: {
    tocLink: {
      color: "fg.default",
      textDecorationLine: "underline",
      textUnderlineOffset: "0.2em",
      borderRadius: "1",
      _hover: { color: "action.link.fg" },
      _focusVisible: focus,
    },
    root: {
      padding: "clamp(1.5rem, 5vw, 3.25rem)",
      background: "bg.surface",
      color: "fg.default",
      borderRadius: "1.75rem",
      boxShadow: "0 30px 60px -34px rgb(11 27 43 / 0.35)",
      _articleCompact: { padding: "1.4rem 1.15rem 1.6rem", borderRadius: "1.25rem" },
    },
    header: {
      display: "grid",
      gap: "4",
      paddingBottom: "6",
      marginBottom: "6",
      borderBottom: "2px solid token(colors.border.strong)",
      _articleCompact: { paddingBottom: "1.6rem", marginBottom: "5" },
    },
    title: { margin: "0", textStyle: "heading.document" },
    section: {
      marginTop: "7",
      scrollMarginTop: "1.5rem",
      _articleCompact: { scrollMarginTop: "calc(4.5rem + env(safe-area-inset-top, 0px))" },
    },
    heading: {
      margin: "0 0 0.6rem",
      paddingLeft: "3",
      borderLeft: "4px solid token(colors.pink.1)",
      textStyle: "heading.prose",
    },
    paragraph: { textStyle: "body.document", margin: "0.5rem 0 0" },
    list: {
      textStyle: "body.document",
      margin: "0.5rem 0 0",
      paddingLeft: "6",
      listStyleType: "disc",
      "&[data-ordered]": { listStyleType: "decimal" },
    },
    table: { borderCollapse: "collapse", width: "100%", marginTop: "3", textStyle: "body.sm" },
    tableLabel: {
      width: "32%",
      padding: "0.6rem 0.75rem",
      background: "bg.subtle",
      textAlign: "start",
      verticalAlign: "top",
      borderBottom: "1px solid token(colors.border.default)",
      _articleCompact: { display: "block", width: "100%", borderBottom: "0" },
    },
    tableValue: {
      padding: "0.6rem 0.75rem",
      textAlign: "start",
      verticalAlign: "top",
      borderBottom: "1px solid token(colors.border.default)",
      _articleCompact: { display: "block", width: "100%" },
    },
    toc: {
      marginBottom: "7",
      padding: "1rem 1.25rem",
      borderRadius: "1rem",
      background: "bg.subtle",
      _articleCompact: { marginBottom: "6" },
    },
    summary: { textStyle: "label", cursor: "pointer", _focusVisible: focus },
    tocList: {
      margin: "0.6rem 0 0",
      paddingLeft: "1.4rem",
      columns: "2 14rem",
      listStyleType: "decimal",
      textStyle: "body.document",
      _articleCompact: { columns: "1", lineHeight: "2.2" },
    },
    footer: {
      marginTop: "8",
      paddingTop: "6",
      borderTop: "1px dashed token(colors.border.default)",
      display: "flex",
      flexWrap: "wrap",
      gap: "0.75rem 1.5rem",
      justifyContent: "space-between",
      alignItems: "center",
    },
  },
});
