import { defineSlotRecipe } from "@pandacss/dev";
import { focus } from "../control";
export const avatarGroup = defineSlotRecipe({
  className: "avatar-group",
  slots: ["frame", "summary", "root", "item", "text", "name", "detail", "value", "marker"],
  base: {
    frame: { display: "flex", alignItems: "center", gap: "3", minWidth: 0 },
    summary: { display: "grid", flexShrink: 0 },
    root: {
      flex: "1 1 auto",
      containerType: "inline-size",
      containerName: "animic-avatar-group",
      minWidth: 0,
      _avatarGroupNarrow: {
        flex: "1 1 auto",
        justifyContent: "space-between",
        border: "0",
        background: "bg.subtle",
        padding: "0.15rem 0.3rem",
      },
      display: "flex",
      alignItems: "center",
      justifyContent: "start",
      gap: "2",
      listStyle: "none",
      margin: "0",
      padding: "1",
      border: "2px solid token(colors.border.default)",
      borderRadius: "full",
      background: "bg.surface",
      overflowX: "auto",
      _focusVisible: focus,
    },
    item: {
      position: "relative",
      display: "flex",
      alignItems: "center",
      gap: "2",
      padding: "0.1rem 0.4rem",
      minWidth: 0,
      borderRadius: "full",
      "&[data-current]": { background: "bg.accent.primary" },
    },
    text: { minWidth: 0, display: "grid", _avatarGroupCompact: { display: "none" } },
    name: {
      textStyle: "label.supporting",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    detail: { textStyle: "caption", whiteSpace: "nowrap", color: "fg.supporting" },
    value: {
      marginInlineStart: "auto",
      textStyle: "numeric.supporting",
      whiteSpace: "nowrap",
      _avatarGroupCompact: { fontSize: "0.85rem" },
    },
    marker: {
      position: "absolute",
      top: "-0.45rem",
      left: "1.6rem",
      display: "grid",
      placeItems: "center",
      minWidth: "1.3rem",
      height: "1.3rem",
      paddingInline: "1",
      borderRadius: "full",
      background: "bg.inverse",
      color: "fg.inverse",
      textStyle: "code.compact",
      fontSize: "0.62rem",
    },
  },
  variants: {
    presentation: {
      compact: {},
      expanded: {
        text: { _avatarGroupCompact: { display: "grid" } },
        frame: { display: "block" },
        root: {
          justifyContent: "safe center",
          flexWrap: "nowrap",
          padding: "0.8rem",
          borderRadius: "1.4rem",
          _avatarGroupNarrow: {
            background: "bg.surface",
            border: "2px solid token(colors.border.default)",
            padding: "2",
            justifyContent: "start",
          },
        },
        item: {
          flex: "0 0 12.5rem",
          padding: "0.45rem 0.8rem 0.45rem 0.45rem",
          background: "bg.subtle",
          border: "2px solid transparent",
          "&[data-current]": { background: "bg.surface", borderColor: "accent.primary" },
          transition: "background 300ms, transform 400ms cubic-bezier(.3,1.6,.5,1), opacity 300ms",
          "&[data-state=pending]": { opacity: "0.55" },
          "&[data-state=active]": {
            background: "bg.surface",
            borderColor: "accent.primary",
            transform: "translateY(-3px)",
            boxShadow:
              "0 10px 22px -12px color-mix(in srgb, token(colors.accent.primary) 70%, transparent)",
          },
          "&[data-state=complete]": { background: "bg.surface", borderColor: "border.default" },
          _motionReduce: { transition: "none" },
          _avatarGroupNarrow: { flexBasis: "auto" },
        },
      },
    },
  },
});
