import { defineSlotRecipe } from "@pandacss/dev";
import { focus } from "../control";
export const choiceCard = defineSlotRecipe({
  className: "choice-card",
  slots: ["root", "media", "body", "indicator"],
  base: {
    root: {
      position: "relative",
      display: "grid",
      width: "100%",
      minWidth: 0,
      padding: "0",
      border: "2px solid token(colors.border.default)",
      borderRadius: "1rem",
      overflow: "hidden",
      background: "bg.surface",
      color: "fg.default",
      textAlign: "start",
      cursor: "pointer",
      _focusVisible: focus,
      _hover: { borderColor: "accent.primary" },
      _pressed: {
        borderColor: "accent.primary",
        boxShadow: "0 0 0 2px color-mix(in srgb, token(colors.accent.primary) 16%, transparent)",
      },
      _disabled: { opacity: "0.5", cursor: "not-allowed" },
    },
    media: {
      width: "100%",
      aspectRatio: "4 / 3",
      objectFit: "cover",
      display: "grid",
      placeItems: "center",
      alignContent: "center",
      gap: "2",
      color: "fg.muted",
      overflow: "hidden",
      background: "bg.subtle",
    },
    indicator: {
      position: "absolute",
      insetBlockStart: "2",
      insetInlineEnd: "2",
      width: "1.35rem",
      height: "1.35rem",
      display: "grid",
      placeItems: "center",
      borderRadius: "full",
      background: "accent.primary",
      color: "fg.inverse",
      textStyle: "caption",
    },
    body: { display: "grid", gap: "1", padding: "3", textStyle: "label.supporting" },
  },
});
