import { defineSlotRecipe } from "@pandacss/dev";
export const comparison = defineSlotRecipe({
  className: "comparison",
  slots: [
    "root",
    "header",
    "images",
    "first",
    "second",
    "tools",
    "history",
    "actions",
    "heading",
    "preferences",
    "decoration",
    "artwork",
    "caption",
    "description",
  ],
  base: {
    artwork: { minHeight: 0, minWidth: 0, display: "grid", placeItems: "center" },
    caption: {
      display: "flex",
      flexWrap: "wrap",
      alignItems: "center",
      justifyContent: "center",
      gap: "2",
      textAlign: "center",
      minWidth: 0,
    },
    description: { _comparisonCompact: { display: "none" } },
    decoration: { position: "absolute", inset: "0", pointerEvents: "none" },
    heading: { _comparisonCompact: { display: "none" } },
    preferences: { minWidth: 0 },
    header: { gridArea: "1 / 1 / 2 / -1", _comparisonCompact: { display: "none" } },
    root: {
      padding: "1.1rem",
      layerStyle: "surface.raised",
      borderWidth: "2",
      borderRadius: "1.6rem",
      _comparisonCompact: {
        padding: "0",
        border: "0",
        borderRadius: "0",
        background: "transparent",
        boxShadow: "none",
        gap: "3",
      },
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr)",
      gridTemplateRows: "auto minmax(min-content, 1fr) auto",
      gap: "5",
      minHeight: "min-content",
      flex: "1 1 auto",
      _comparisonWide: { gridTemplateColumns: "minmax(0, 1fr) 12.25rem" },
    },
    images: {
      position: "relative",
      gridArea: "2 / 1",
      minHeight: "0",
      display: "grid",
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
      gridTemplateRows: "auto auto",
      alignItems: "center",
      alignContent: "center",
      gap: "clamp(0.75rem, 2vw, 1.5rem)",
      minWidth: 0,
      _comparisonNarrow: {
        justifyContent: "center",
        gridTemplateColumns: "repeat(2, min(calc(50% - 0.75rem), calc(30svh * 13 / 19)))",
      },
      _comparisonCompact: {
        paddingInline: "0",
        alignItems: "start",
        justifyContent: "center",
        gridTemplateColumns: "repeat(2, min(calc(50% - 5px), calc(25svh * 13 / 19)))",
        gap: "0.625rem",
      },
    },
    first: {
      display: "grid",
      gridTemplateRows: "subgrid",
      gridRow: "1 / span 2",
      gridColumn: "1",
      minWidth: 0,
      width: "100%",
      justifySelf: "end",
    },
    second: {
      display: "grid",
      gridTemplateRows: "subgrid",
      gridRow: "1 / span 2",
      gridColumn: "2",
      minWidth: 0,
      width: "100%",
      justifySelf: "start",
    },
    tools: {
      gridArea: "3 / 1",
      minWidth: 0,
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr) minmax(0, 12rem)",
      alignItems: "end",
      gap: "4",
      paddingTop: "0.9rem",
      borderTop: "2px dashed token(colors.border.default)",
      _comparisonWide: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "stretch",
        gridArea: "2 / 2",
        borderLeft: "2px dashed token(colors.border.default)",
        paddingLeft: "5",
        paddingTop: "0",
        borderTop: "0",
      },
      _comparisonCompact: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1.8fr)",
        alignItems: "center",
        gap: "3",
        paddingTop: "0",
        borderTop: "0",
      },
    },
    history: { minWidth: 0 },
    actions: {
      minWidth: 0,
      display: "grid",
      gap: "2",
    },
  },
});
