import { defineSlotRecipe } from "@pandacss/dev";
import { focus } from "../control";
export const media = defineSlotRecipe({
  className: "media",
  slots: [
    "description",
    "root",
    "viewport",
    "image",
    "label",
    "caption",
    "trigger",
    "placeholder",
    "decoration",
    "footer",
  ],
  base: {
    footer: {
      position: "absolute",
      insetInline: "3",
      bottom: "3",
      display: "grid",
      gap: "2",
      padding: "0.55rem 0.8rem 0.65rem",
      borderRadius: "0.8rem",
      background: "color-mix(in srgb, token(colors.bg.inverse) 82%, transparent)",
      color: "fg.inverse",
      backdropFilter: "blur(4px)",
      _mediaCompact: { insetInline: "1", bottom: "1", padding: "0.35rem" },
    },
    description: {
      textStyle: "caption",
      fontWeight: "bold",
      color: "fg.supporting",
      _mediaCompact: { display: "none" },
    },
    decoration: { position: "absolute", inset: "0", pointerEvents: "none" },
    placeholder: {
      height: "100%",
      minHeight: "100%",
      display: "grid",
      placeContent: "center",
      justifyItems: "center",
      gap: "4",
      padding: "3",
      textAlign: "center",
      color: "fg.supporting",
      background: "bg.subtle",
      backgroundImage: "radial-gradient(token(colors.border.default) 1px, transparent 1px)",
      backgroundSize: "16px 16px",
      "& > svg": {
        width: "38%",
        maxWidth: "100%",
        height: "auto",
        _mediaCompact: { width: "34%" },
      },
    },
    root: {
      "--animic-media-radius": "1rem",
      "--animic-media-border-width": "token(borderWidths.2)",
      position: "relative",
      width: "100%",
      minWidth: 0,
      border: "var(--animic-media-border-width) solid token(colors.border.default)",
      borderRadius: "var(--animic-media-radius)",
      background: "bg.subtle",
      isolation: "isolate",
    },
    viewport: {
      position: "absolute",
      inset: "0",
      margin: "0",
      borderRadius: "calc(var(--animic-media-radius) - var(--animic-media-border-width))",
      overflow: "hidden",
      clipPath: "border-box",
    },
    image: {
      display: "block",
      width: "100%",
      height: "100%",
      objectFit: "cover",
      objectPosition: "50% 15%",
      "&[data-entering]": {
        animation: "mediaEnter 800ms cubic-bezier(.3,1.6,.5,1) 150ms both",
        _motionReduce: { animation: "none" },
      },
    },
    label: { position: "absolute", insetBlockStart: "3", insetInlineStart: "3", zIndex: 1 },
    caption: {
      position: "absolute",
      insetInline: "0",
      bottom: "0",
      padding: "clamp(1rem, 3vw, 1.5rem)",
      paddingBlockStart: "3rem",
      color: "fg.inverse",
      background: "linear-gradient(transparent, token(colors.fg.default))",
    },
    trigger: {
      position: "absolute",
      inset: "0",
      width: "100%",
      height: "100%",
      border: "0",
      background: "transparent",
      cursor: "zoom-in",
      borderRadius: "inherit",
      _focusVisible: { ...focus, outlineOffset: "-4px" },
    },
  },
  variants: {
    size: {
      fluid: {},
      preview: { root: { width: "min(100%, 12rem)", marginInline: "auto" } },
    },
    appearance: {
      standard: {},
      inverse: {
        root: {
          "--animic-media-border-width": "token(borderWidths.3)",
          borderColor: "bg.surface",
          background: "bg.surface",
        },
      },
      accented: {
        root: {
          "--animic-media-border-width": "token(borderWidths.3)",
          "--animic-media-radius": "1.2rem",
          borderColor: "bg.surface",
          background: "bg.surface",
          boxShadow: "0 8px 0 token(colors.accent.primary), 0 30px 60px -20px rgb(0 0 0 / 0.6)",
        },
      },
    },
    presentation: {
      standard: {},
      captioned: {
        root: { containerType: "inline-size", maxHeight: "24rem" },
        caption: {
          padding: "4rem 1rem 1rem",
          background:
            "linear-gradient(to top, rgb(11 27 43 / 0.9), rgb(11 27 43 / 0.72) 40%, rgb(11 27 43 / 0.45))",
          backdropFilter: "blur(14px)",
          maskImage:
            "linear-gradient(to top, #000 32%, rgb(0 0 0 / 0.78) 50%, rgb(0 0 0 / 0.42) 70%, rgb(0 0 0 / 0.14) 88%, transparent)",
        },
      },
    },
    aspect: {
      square: { root: { aspectRatio: "1" } },
      portrait: { root: { aspectRatio: "13 / 19" } },
      landscape: { root: { aspectRatio: "16 / 9" } },
    },
    fit: { cover: {}, contain: { image: { objectFit: "contain", objectPosition: "center" } } },
  },
  defaultVariants: { aspect: "square", fit: "cover" },
});
