import { defineSlotRecipe } from "@pandacss/dev";

export const navigationBar = defineSlotRecipe({
  className: "navigation-bar",
  slots: ["root", "brand", "content", "links", "primaryActions", "actions", "label", "indicator"],
  base: {
    root: {
      "&[data-initial-visible]": {
        _navigationCompact: { transform: "none", visibility: "visible", transition: "none" },
      },
      position: "fixed",
      insetBlockStart: "0",
      insetInlineEnd: "0",
      zIndex: "navigation",
      display: "flex",
      alignItems: "center",
      gap: "clamp(1rem, 3.5vw, 3.5rem)",
      maxWidth: "100%",
      "--animic-button-full-label-display": "inline",
      "--animic-button-compact-label-display": "none",
      "&[data-navigation-labels=short]": {
        "--animic-button-full-label-display": "none",
        "--animic-button-compact-label-display": "inline",
      },
      "&[data-navigation-layout=stacked]": { columnGap: "7" },
      "--animic-navigation-brand-space":
        "calc(clamp(1.25rem, 4vw, 3rem) + clamp(8rem, 12vw, 11rem) + token(spacing.5))",
      _navigationWide: { maxWidth: "calc(100% - var(--animic-navigation-brand-space))" },
      _navigationConstrained: {
        width: "calc(100% - var(--animic-navigation-brand-space))",
        gap: "5",
        paddingInline: "5",
      },
      paddingBlock: "calc(token(spacing.5) * 1.4)",
      paddingInline: "clamp(1.25rem, 4vw, 4.5rem)",
      background: "bg.surface",
      color: "fg.default",
      borderEndStartRadius: "3",
      boxShadow: "soft.1",
      _navigationDense: {
        insetInline: "0",
        justifyContent: "center",
        borderEndEndRadius: "1.25rem",
        gap: "5",
        paddingInline: "5",
        alignItems: "center",
      },
      _navigationCompact: {
        insetInline: "0",
        paddingBlockStart: "calc(0.375rem + env(safe-area-inset-top, 0px))",
        paddingBlockEnd: "0.375rem",
        transform: "none",
        visibility: "visible",
        transition: "transform 350ms cubic-bezier(0.2, 0.9, 0.3, 1)",
        _motionReduce: { transition: "none" },
        paddingInline: "5",
        minHeight: "calc(56px + env(safe-area-inset-top, 0px))",
        borderEndStartRadius: "1.25rem",
        borderEndEndRadius: "1.25rem",
        justifyContent: "space-between",
        flexWrap: "nowrap",
        "&[data-navigation-overflow]": { flexWrap: "wrap" },
        "&[data-navigation-layout=stacked]": { columnGap: "2" },
        gap: "2",
      },
    },
    brand: {
      "[data-initial-visible] &": {
        _navigationWide: {
          opacity: 1,
          visibility: "visible",
          transform: "none",
          transition: "none",
        },
      },
      display: "none",
      "& > a": { width: "100%" },
      _navigationWide: {
        display: "block",
        opacity: 1,
        visibility: "visible",
        transform: "none",
        transition:
          "opacity 400ms ease 100ms, transform 500ms cubic-bezier(0.3, 1.6, 0.5, 1) 100ms",
        _motionReduce: { transition: "none" },
        position: "fixed",
        insetBlockStart: "5",
        insetInlineStart: "clamp(1.25rem, 4vw, 3rem)",
        width: "clamp(8rem, 12vw, 11rem)",
      },
      _navigationCompact: {
        display: "flex",
        alignItems: "center",
        flex: "0 0 auto",
        width: "6.5rem",
        minWidth: "control.0",
        maxWidth: "6.5rem",
      },
    },
    content: {
      display: "flex",
      flexWrap: "wrap",
      alignItems: "center",
      gap: "clamp(1rem, 3.5vw, 3.5rem)",
      minWidth: 0,
      flex: "0 1 auto",
      _navigationConstrained: { gap: "7", flexGrow: 1 },
      _navigationDense: { gap: "4", flexGrow: 0 },
      _navigationCompact: { gap: "2", flex: "0 1 auto", marginInlineStart: "auto" },
      "[data-navigation-layout=inline] &": { flexWrap: "nowrap" },
      "[data-navigation-layout=stacked] &": { flexDirection: "column", alignItems: "start" },
    },
    links: {
      position: "relative",
      display: "flex",
      alignItems: "center",
      flexShrink: 0,
      gap: "clamp(1rem, 3.5vw, 3.5rem)",
      _navigationConstrained: { gap: "5", flexGrow: 1, justifyContent: "space-around" },
      _navigationDense: { gap: "4", flexGrow: 0 },
      "& > a": { flexShrink: 0, whiteSpace: "nowrap" },
      "[data-indicator-ready] & > a::after": { display: "none" },
      "[data-navigation-overflow] &": { maxWidth: "100%", flexWrap: "wrap" },
      _navigationCompact: { display: "none" },
    },
    primaryActions: {
      display: "flex",
      alignItems: "center",
      gap: "3",
      flexShrink: 0,
      "& > *": { flexShrink: 0, whiteSpace: "nowrap" },
      "[data-navigation-overflow] & > *": { maxWidth: "100%", whiteSpace: "normal", flexShrink: 1 },
      _navigationCompact: { gap: "2" },
      "[data-navigation-overflow] &": { maxWidth: "100%", flexWrap: "wrap" },
    },
    actions: {
      display: "flex",
      alignItems: "center",
      gap: "3",
      flexShrink: 0,
      borderInlineStart: "2px solid token(colors.border.default)",
      paddingInlineStart: "6",
      _navigationDense: { paddingInlineStart: "5" },
      "[data-navigation-layout=stacked] &": { paddingInlineStart: "7" },
      _navigationCompact: {
        minWidth: 0,
        borderInlineStartWidth: "0",
        paddingInlineStart: "0",
        "[data-navigation-layout=stacked] &": { paddingInlineStart: "0" },
      },
    },
    indicator: {
      position: "absolute",
      pointerEvents: "none",
      left: "0",
      top: "0",
      height: "3px",
      "--animic-indicator-duration": "300ms",
      "--animic-indicator-easing": "cubic-bezier(0.2, 0, 0, 1)",
      borderRadius: "full",
      background: "accent.primary",
      visibility: "hidden",
      opacity: 1,
      "[data-indicator-ready] &": { visibility: "visible" },
      _motionReduce: { "--animic-indicator-duration": "0ms" },
      _navigationCompact: { display: "none" },
    },
    label: { _navigationCompact: { display: "none" } },
  },
  variants: {
    brandHidden: {
      true: {
        brand: {
          _navigationWide: {
            opacity: 0,
            visibility: "hidden",
            transform: "translateY(-1rem) rotate(-4deg)",
            transition:
              "opacity 400ms ease, transform 500ms cubic-bezier(0.3, 1.6, 0.5, 1), visibility 0ms linear 500ms",
            _motionReduce: { transition: "none" },
          },
        },
      },
      false: {},
    },
    compactHidden: {
      true: {
        root: {
          _navigationCompact: {
            transform: "translateY(-110%)",
            visibility: "hidden",
            transition:
              "transform 350ms cubic-bezier(0.2, 0.9, 0.3, 1), visibility 0ms linear 350ms",
            _motionReduce: { transition: "none" },
          },
        },
      },
      false: {},
    },
  },
});
