import { defineSlotRecipe } from "@pandacss/dev";

// 選択肢から1つ選ぶ（開くと一覧が出る）
export const select = defineSlotRecipe({
  className: "select",
  description: "選択肢が多いときの選択。少ない（4つ以下）なら並べて見せる方を優先する",
  slots: [
    "root",
    "label",
    "control",
    "trigger",
    "valueText",
    "indicator",
    "positioner",
    "content",
    "item",
    "itemText",
    "itemIndicator",
  ],
  base: {
    root: { display: "grid", gap: "2", minWidth: "0" },
    label: { textStyle: "label", color: "fg.default" },
    control: { position: "relative" },
    trigger: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "2",
      width: "full",
      minHeight: "12",
      px: "4",
      textStyle: "body.md",
      color: "fg.default",
      bg: "bg.surface",
      borderWidth: "thick",
      borderStyle: "solid",
      borderColor: "border.default",
      borderRadius: "field",
      cursor: "pointer",
      _open: { borderColor: "border.strong" },
      _focusVisible: { borderColor: "border.strong" },
      _disabled: { bg: "bg.sunken", color: "fg.subtle", cursor: "default" },
    },
    valueText: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      _placeholderShown: { color: "fg.subtle" },
    },
    indicator: {
      color: "fg.muted",
      transitionProperty: "transform",
      transitionDuration: "fast",
      _open: { transform: "rotate(180deg)" },
    },
    positioner: { zIndex: "overlay" },
    content: {
      layerStyle: "overlay",
      display: "grid",
      gap: "0.5",
      p: "1.5",
      borderRadius: "panel",
      maxHeight: "80",
      overflowY: "auto",
      outline: "none",
      _open: { animationStyle: "fade-in" },
    },
    item: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "2",
      px: "3",
      py: "2",
      borderRadius: "chip",
      textStyle: "body.sm",
      cursor: "pointer",
      _highlighted: { bg: "bg.sunken" },
      _checked: { color: "accent.default", fontWeight: "bold" },
      _disabled: { color: "fg.subtle", cursor: "default" },
    },
    itemText: {},
    itemIndicator: { color: "accent.default" },
  },
});
