import { defineSlotRecipe } from "@pandacss/dev";
import { focus } from "../control";
export const thumbnailList = defineSlotRecipe({
  className: "thumbnail-list",
  slots: [
    "root",
    "item",
    "button",
    "image",
    "label",
    "empty",
    "emptyDetail",
    "emptyCompact",
    "selected",
  ],
  base: {
    selected: {
      position: "absolute",
      top: "1",
      right: "1",
      width: "1.1rem",
      height: "1.1rem",
      display: "grid",
      placeItems: "center",
      borderRadius: "full",
      color: "fg.inverse",
      background: "accent.primary",
    },
    emptyDetail: { _thumbnailLabelCompact: { display: "none" } },
    emptyCompact: { display: "none", _thumbnailLabelCompact: { display: "inline" } },
    root: {
      display: "flex",
      flexWrap: "wrap",
      alignContent: "start",
      gap: "2",
      margin: "0",
      padding: "0.45rem 0.35rem 0.6rem",
      listStyle: "none",
      maxHeight: "26rem",
      overflowY: "auto",
      _thumbnailCompact: { flexWrap: "nowrap", overflowX: "auto", paddingBottom: "1" },
    },
    item: { width: "calc(50% - 0.25rem)", flexShrink: 0, _thumbnailCompact: { width: "3.5rem" } },
    button: {
      display: "grid",
      position: "relative",
      width: "100%",
      aspectRatio: "13 / 19",
      transition: "transform 200ms cubic-bezier(.3,1.6,.5,1), box-shadow 200ms ease",
      "&:hover:not(:disabled)": { transform: "translateY(-3px) rotate(-2deg)" },
      _motionReduce: { transition: "none", "&:hover:not(:disabled)": { transform: "none" } },
      _thumbnailCompact: { aspectRatio: "1" },
      placeItems: "center",
      padding: "0",
      border: "2px solid token(colors.border.default)",
      borderRadius: "0.75rem",
      overflow: "hidden",
      background: "bg.subtle",
      color: "fg.muted",
      textStyle: "caption",
      cursor: "pointer",
      _pressed: {
        borderColor: "accent.primary",
        boxShadow: "0 0 0 2px color-mix(in srgb, token(colors.accent.primary) 20%, transparent)",
      },
      _focusVisible: focus,
      _disabled: { cursor: "default" },
    },
    image: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
    label: {
      position: "absolute",
      insetBlockEnd: "1",
      insetInlineStart: "1",
      borderRadius: "full",
      padding: "0 0.4rem",
      background: "bg.surface",
      textStyle: "caption",
      color: "fg.default",
    },
    empty: {
      display: "grid",
      placeItems: "center",
      textAlign: "center",
      minHeight: "16.5rem",
      padding: "4",
      border: "2px dashed token(colors.border.default)",
      borderRadius: "1rem",
      color: "fg.supporting",
      textStyle: "caption",
      _thumbnailCompact: { minHeight: "2rem", maxWidth: "22rem", padding: "2" },
    },
  },
  variants: {
    entering: {
      true: {
        button: {
          animation: "thumbnailEnter 500ms cubic-bezier(.3,1.6,.5,1)",
          _motionReduce: { animation: "none" },
        },
      },
    },
  },
});
