import { defineSlotRecipe } from "@pandacss/dev";
import { focus } from "../control";
export const tokenInput = defineSlotRecipe({
  className: "token-input",
  slots: [
    "root",
    "content",
    "input",
    "footer",
    "suggestions",
    "option",
    "token",
    "label",
    "actions",
    "adjustment",
    "empty",
    "shortcut",
  ],
  base: {
    empty: { padding: "3", color: "fg.muted", textStyle: "caption" },
    shortcut: {
      border: "1px solid token(colors.border.default)",
      borderRadius: "1",
      paddingInline: "1",
      textStyle: "caption",
      color: "fg.muted",
    },
    root: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      minHeight: "10rem",
      flex: "1 1 auto",
      border: "2px solid token(colors.border.default)",
      borderRadius: "1.1rem",
      padding: "1rem",
      background: "bg.surface",
      _focusWithin: { borderColor: "accent.primary" },
      _tokenInputCompact: {
        background: "bg.subtle",
        borderColor: "transparent",
        minHeight: "7rem",
      },
    },
    content: {
      display: "flex",
      flexWrap: "wrap",
      alignContent: "start",
      alignItems: "start",
      gap: "2",
      flex: "1 1 auto",
      overflowY: "auto",
      minHeight: "0",
    },
    input: {
      flex: "1 1 8rem",
      minWidth: "4rem",
      maxWidth: "100%",
      padding: "1",
      background: "transparent",
      color: "fg.default",
      textStyle: "body.md",
      border: "0",
      outline: "none",
      _placeholder: { color: "fg.subtle" },
      _disabled: { color: "disabled.fg", cursor: "not-allowed" },
    },
    footer: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: "3",
      paddingTop: "3",
      textStyle: "caption",
      color: "fg.supporting",
    },
    suggestions: {
      "&[hidden]": { display: "none" },
      position: "absolute",
      zIndex: "navigation",
      insetInline: "0",
      top: "100%",
      marginTop: "2",
      display: "grid",
      padding: "2",
      borderRadius: "1rem",
      background: "bg.surface",
      boxShadow: "soft.2",
      border: "1px solid token(colors.border.default)",
      maxHeight: "17rem",
      overflowY: "auto",
    },
    option: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "space-between",
      gap: "2",
      textAlign: "start",
      border: "0",
      borderRadius: "2",
      padding: "3",
      background: "transparent",
      color: "fg.default",
      textStyle: "label.supporting",
      cursor: "pointer",
      _highlighted: { background: "bg.accent.primary" },
      _focusVisible: focus,
    },
    token: {
      display: "inline-flex",
      alignItems: "center",
      gap: "1",
      minWidth: 0,
      maxWidth: "100%",
      padding: "0.15rem 0.35rem 0.15rem 0.65rem",
      border: "1px solid token(colors.border.default)",
      borderRadius: "0.8rem",
      background: "bg.subtle",
      color: "fg.default",
    },
    label: {
      border: "0",
      background: "transparent",
      color: "inherit",
      textStyle: "label.supporting",
      overflowWrap: "anywhere",
      cursor: "text",
      padding: "1",
      _focusVisible: focus,
    },
    actions: {
      display: "inline-flex",
      flexDirection: "column",
      gap: "0",
      alignItems: "center",
      flexShrink: 0,
      borderRadius: "full",
      background: "bg.surface",
      border: "1px solid token(colors.border.default)",
      overflow: "hidden",
    },
    adjustment: {
      width: "1.5rem",
      height: "1.5rem",
      display: "grid",
      placeItems: "center",
      padding: "0",
      border: "0",
      borderRadius: "full",
      background: "bg.surface",
      color: "fg.supporting",
      textStyle: "label.supporting",
      cursor: "pointer",
      _focusVisible: focus,
      _disabled: { opacity: "0.4", cursor: "not-allowed" },
    },
  },
  variants: {
    font: {
      body: {},
      code: { input: { textStyle: "code" }, label: { textStyle: "code" } },
    },
    emphasis: {
      normal: {},
      strong: { token: { background: "bg.accent.primary", borderColor: "accent.primary" } },
      weak: { token: { opacity: "0.65" } },
    },
  },
});
