import { defineSlotRecipe, defineStyles } from "@pandacss/dev";
import { focus } from "../control";
// 縦積みは「比較を横に置けない幅」か「高さのある中間幅」で選ぶ。
// 低い横長画面の条件と重ねず、生成CSSの順序でレイアウトが変わらないようにする。
const stackedHeader = defineStyles({
  height: "auto",
  gridTemplateColumns: "minmax(0, 1fr) auto",
  gap: "2",
  padding: "0.2rem 0.875rem 0.7rem",
  background: "bg.surface",
});
const stackedBody = defineStyles({
  display: "flex",
  flexDirection: "column",
  padding: "0.625rem 0.875rem 1.5rem",
});
export const workspace = defineSlotRecipe({
  className: "workspace",
  slots: [
    "root",
    "layout",
    "header",
    "start",
    "detail",
    "center",
    "end",
    "progress",
    "body",
    "editor",
    "grip",
    "editorBody",
    "collapsed",
    "main",
  ],
  base: {
    collapsed: { display: "none" },
    root: { containerType: "inline-size", containerName: "animic-workspace", color: "fg.default" },
    layout: {
      display: "grid",
      gridTemplateRows: "auto auto minmax(0, 1fr)",
      minHeight: "max(100svh, 43.25rem)",
      _workspaceCompact: { minHeight: "100svh" },
      _workspaceDocked: { height: "100svh", minHeight: 0, background: "bg.surface" },
      _workspaceShort: { minHeight: "100svh" },
    },
    header: {
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)",
      alignItems: "center",
      gap: "6",
      minHeight: "4.75rem",
      paddingInline: "clamp(1rem, 3vw, 2rem)",
      _workspaceVertical: stackedHeader,
      _workspaceCompact: { _workspaceTall: stackedHeader },
      _workspaceLandscape: {
        _workspaceHorizontal: {
          gridTemplateColumns: "auto auto minmax(0, 1fr)",
          paddingBlock: "2",
          gap: "3",
        },
      },
    },
    detail: { _workspaceCompact: { display: "none" } },
    start: {
      display: "flex",
      alignItems: "center",
      gap: "3",
      minWidth: 0,
      flexWrap: "wrap",
      _workspaceCompact: { gap: "2" },
      "& img": {
        display: "block",
        width: "7.25rem",
        height: "auto",
        _workspaceNarrow: { width: "4.5rem" },
        _workspaceLandscape: { _workspaceHorizontal: { width: "4.8rem" } },
      },
    },
    center: {
      justifySelf: "center",
      minWidth: 0,
      _workspaceVertical: { justifySelf: "end" },
      _workspaceCompact: { _workspaceTall: { justifySelf: "end" } },
    },
    end: {
      minWidth: 0,
      _workspaceVertical: { gridColumn: "1 / -1" },
      _workspaceCompact: { _workspaceTall: { gridColumn: "1 / -1" } },
    },
    progress: { paddingInline: "clamp(1rem, 3vw, 1.75rem)", height: "0.5rem" },
    body: {
      display: "grid",
      gridTemplateColumns: "clamp(17rem, 25vw, 25rem) minmax(0, 1fr)",
      gap: "1.1rem",
      padding: "1.1rem clamp(1rem, 3vw, 1.75rem) 1.5rem",
      minHeight: "38rem",
      gridTemplateRows: "minmax(0, 1fr)",
      _workspaceShort: { minHeight: "0" },
      _workspaceCompact: { minHeight: "0", _workspaceTall: { _workspaceFlow: stackedBody } },
      _workspaceVertical: {
        minHeight: "0",
        _workspaceFlow: stackedBody,
        _workspaceDocked: {
          display: "grid",
          gridTemplateColumns: "minmax(0, 1fr)",
          gridTemplateRows: "auto minmax(0, 1fr)",
          padding: "0",
          gap: "0",
        },
      },
      _workspaceLandscape: {
        _workspaceHorizontal: {
          display: "grid",
          gridTemplateColumns: "minmax(17rem, 40%) minmax(0, 1fr)",
          padding: "0.5rem 0.875rem 1rem",
          gap: "2",
        },
      },
    },
    editor: {
      display: "flex",
      flexDirection: "column",
      minWidth: 0,
      border: "2px solid token(colors.border.default)",
      borderRadius: "1.6rem",
      background: "bg.surface",
      boxShadow: "soft.1",
      padding: "1.1rem",
      _workspaceDocked: {
        position: "relative",
        gridRow: "2",
        minHeight: "min-content",
        zIndex: "navigation",
        borderBottom: "0",
        borderEndStartRadius: "0",
        borderEndEndRadius: "0",
        padding: "0.9rem 0.875rem max(0.75rem, env(safe-area-inset-bottom, 0px))",
        boxShadow: "0 -14px 34px -20px rgb(11 27 43 / 0.4)",
      },
    },
    grip: {
      display: "none",
      _workspaceDocked: {
        display: "grid",
        placeItems: "center",
        width: "3rem",
        height: "1.5rem",
        position: "absolute",
        top: "-1px",
        left: "50%",
        translate: "-50% 0",
        border: "0",
        background: "transparent",
        touchAction: "none",
        cursor: "pointer",
        _focusVisible: focus,
        "&::after": {
          content: '""',
          width: "2.5rem",
          height: "5px",
          borderRadius: "full",
          background: "border.default",
        },
      },
    },
    editorBody: {
      overflowY: "auto",
      minHeight: 0,
      minWidth: 0,
      flex: "1 1 auto",
      display: "grid",
      _workspaceCompact: { _workspaceFlow: { overflowY: "visible" } },
      _workspaceDocked: { paddingTop: "2", overflowY: "auto" },
    },
    main: {
      minWidth: 0,
      minHeight: 0,
      display: "grid",
      _workspaceVertical: { order: -1 },
      _workspaceCompact: { _workspaceTall: { order: -1 } },
      _workspaceDocked: {
        gridRow: "1",
        padding: "0.625rem 0.875rem 1rem",
        alignContent: "start",
      },
    },
  },
  variants: {
    expanded: {
      false: {
        editor: { _workspaceDocked: { height: "auto", minHeight: "0", paddingTop: "1.3rem" } },
        collapsed: { _workspaceDocked: { display: "grid" } },
        editorBody: { _workspaceDocked: { display: "none" } },
      },
    },
  },
});
